### ISSUE TITLE
Adding Archive Flag to project json

### ISSUE THREAD

**Issue by KPhans** [dluftspring/tap-hellobaton#21]
Hey @dluftspring ! There has been a request to add this field in the `projects_read` endpoint - https://lane.hellobaton.com/api/redoc/#:~:text=null%20%3Cdecimal%3E%20(Cost)-,archived,boolean%20(Archived),-annual_contract_value. 

Added below to `project.json` and tried to push to a branch but unable to do so due to permissions. Let me know what i can do from here to add this in! 

```
"archived": {
      "type": ["boolean", "null"]
    },
```

**Comment by dluftspring** [comment]
Yeah I think people usually fork the repo then raise the PR targeting `main`. I've sent you an invite as a collaborator then I can give you write access - that way you'll just be able to branch of `main` they way you're used to

**Comment by KPhans** [comment]
thanks @dluftspring !
